/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.BoxLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ichinator
 */
public class Main extends javax.swing.JFrame {
    
    ArrayList<String> arrayListIngredients = new ArrayList<>();
    

    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();

        fillJTableCategory();

        fillJTableUsers();

        jComboBoxAddVilleUser.removeAllItems();
        jComboBoxChooseCategorieIngredient.removeAllItems();
        jComboBoxListIngredients.removeAllItems();
        
        
        
        //model.ModelIngredient.selectAllIngredients();

    }

    private void fillJTableCategory() {
        // On remplit jTableCategory avec le ResultSet
        ResultSet result = model.ModelCategorie.selectAllCategory();
        jTableCategory.setModel(DbUtils.resultSetToTableModel(result));
    }

    private void fillJTableUsers() {
        // On remplit jTableCategory avec le ResultSet
        ResultSet resultAllUsers = model.ModelUtilisateurs.selectAllUser();
        jTableUsers.setModel(DbUtils.resultSetToTableModel(resultAllUsers));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPanelCours = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddCategory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddCategory = new javax.swing.JTextArea();
        jTextFieldAddCategory = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCategory = new javax.swing.JTable();
        jTextFieldSearchCategory = new javax.swing.JTextField();
        jButtonSearchCategory = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldAddRecette = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaAddRecette = new javax.swing.JTextArea();
        jButtonAddRecette = new javax.swing.JButton();
        jTextFieldListIngredients = new javax.swing.JTextField();
        jComboBoxListIngredients = new javax.swing.JComboBox<>();
        jButtonAddIngredientToRecette = new javax.swing.JButton();
        jLabelListIngredients = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelNomIngrédient = new javax.swing.JLabel();
        jButtonAddIngredient = new javax.swing.JButton();
        jTextFieldAddIngrédient = new javax.swing.JTextField();
        jLabelChooseCategorieIngredient = new javax.swing.JLabel();
        jComboBoxChooseCategorieIngredient = new javax.swing.JComboBox<>();
        jTextFieldChooseCategorieIngredient = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldAddVilleUser = new javax.swing.JTextField();
        jComboBoxAddVilleUser = new javax.swing.JComboBox<>();
        jButtonAddAdmin = new javax.swing.JButton();
        jLabelAddAdminNom = new javax.swing.JLabel();
        jLabelAddAdminPrenom = new javax.swing.JLabel();
        jTextFieldAddAdminPrenom = new javax.swing.JTextField();
        jTextFieldAddAdminNom = new javax.swing.JTextField();
        jTextFieldAddAdminJour = new javax.swing.JTextField();
        jTextFieldAddAdminMois = new javax.swing.JTextField();
        jTextFieldAddAdminAnnee = new javax.swing.JTextField();
        jLabelAddAdminDateNaissance = new javax.swing.JLabel();
        jLabelAddAdminMail = new javax.swing.JLabel();
        jTextFieldAddAdminMail = new javax.swing.JTextField();
        jLabelAddAdminPassword = new javax.swing.JLabel();
        jPasswordFieldAddAdminPassword = new javax.swing.JPasswordField();
        jPasswordFieldAddAdminPasswordConfirm = new javax.swing.JPasswordField();
        jLabelAddAdminPasswordConfirm = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabelAddAdminAdresse = new javax.swing.JLabel();
        jTextFieldAddAdminAdresse = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButtonSearchUsers = new javax.swing.JButton();
        jTextFieldSearchUsers = new javax.swing.JTextField();
        jCheckBoxAdmin = new javax.swing.JCheckBox();
        jCheckBoxCuisinier = new javax.swing.JCheckBox();
        jCheckBoxClient = new javax.swing.JCheckBox();
        jCheckBoxAll = new javax.swing.JCheckBox();
        jCheckBoxNoOne = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1511, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        jTabbedPanelCours.addTab("Accueil", jPanel1);

        jButtonAddCategory.setText("Ajouter la catégorie");
        jButtonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCategoryActionPerformed(evt);
            }
        });

        jTextAreaAddCategory.setColumns(20);
        jTextAreaAddCategory.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddCategory);

        jTableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCategory);

        jButtonSearchCategory.setText("Chercher");
        jButtonSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextFieldSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonSearchCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddCategory)
                .addGap(189, 189, 189))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonAddCategory)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSearchCategory))
                        .addContainerGap())))
        );

        jTabbedPanelCours.addTab("Les catégories", jPanel4);

        jTextAreaAddRecette.setColumns(20);
        jTextAreaAddRecette.setRows(5);
        jScrollPane4.setViewportView(jTextAreaAddRecette);

        jButtonAddRecette.setText("Ajouter la recette");
        jButtonAddRecette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRecetteActionPerformed(evt);
            }
        });

        jTextFieldListIngredients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldListIngredientsKeyPressed(evt);
            }
        });

        jComboBoxListIngredients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddIngredientToRecette.setText("Ajouter l'ingrédient");
        jButtonAddIngredientToRecette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIngredientToRecetteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jTextFieldAddRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jButtonAddRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButtonAddIngredientToRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jTextFieldListIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334)
                        .addComponent(jComboBoxListIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelListIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextFieldAddRecette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelListIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldListIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxListIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddIngredientToRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPanelCours.addTab("Les recettes", jPanel3);

        jLabelNomIngrédient.setText("Nom de l'ingrédient");

        jButtonAddIngredient.setText("Ajouter à la base");
        jButtonAddIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIngredientActionPerformed(evt);
            }
        });

        jLabelChooseCategorieIngredient.setText("Catégorie de l'ingrédient");

        jComboBoxChooseCategorieIngredient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldChooseCategorieIngredient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldChooseCategorieIngredientKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomIngrédient)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabelChooseCategorieIngredient)
                                .addGap(43, 43, 43)
                                .addComponent(jTextFieldChooseCategorieIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddIngrédient)
                            .addComponent(jComboBoxChooseCategorieIngredient, 0, 143, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jButtonAddIngredient)))
                .addContainerGap(743, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddIngrédient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomIngrédient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChooseCategorieIngredient)
                    .addComponent(jComboBoxChooseCategorieIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChooseCategorieIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButtonAddIngredient)
                .addGap(278, 278, 278))
        );

        jTabbedPanelCours.addTab("Les ingrédients", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1511, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        jTabbedPanelCours.addTab("Les cours", jPanel7);

        jTextFieldAddVilleUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddVilleUserActionPerformed(evt);
            }
        });
        jTextFieldAddVilleUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddVilleUserKeyPressed(evt);
            }
        });

        jComboBoxAddVilleUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddAdmin.setText("Créer l'administrateur");
        jButtonAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAdminActionPerformed(evt);
            }
        });

        jLabelAddAdminNom.setText("Nom");

        jLabelAddAdminPrenom.setText("Prenom");

        jTextFieldAddAdminJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddAdminJourActionPerformed(evt);
            }
        });

        jLabelAddAdminDateNaissance.setText("Date de naissance");

        jLabelAddAdminMail.setText("Mail");

        jLabelAddAdminPassword.setText("Mot de passe");

        jLabelAddAdminPasswordConfirm.setText("Confirmer mot de passe");

        jLabel1.setText("Les informations suivantes ne seront insérées que si l'utilisateur n'est pas dans la base de données mais elles sont tout de même requises");

        jLabelAddAdminAdresse.setText("Adresse");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddAdminDateNaissance)
                            .addComponent(jLabelAddAdminPassword)
                            .addComponent(jLabelAddAdminAdresse))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPasswordFieldAddAdminPassword)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextFieldAddAdminJour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAddAdminMois, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAddAdminAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAddAdminMail)
                                    .addComponent(jLabelAddAdminPasswordConfirm))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAddAdminMail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldAddAdminPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldAddAdminAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabelAddAdminNom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldAddAdminNom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabelAddAdminPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jTextFieldAddAdminPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(jButtonAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jTextFieldAddVilleUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(jComboBoxAddVilleUser, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddAdminNom)
                    .addComponent(jLabelAddAdminPrenom)
                    .addComponent(jTextFieldAddAdminPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddAdminNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddAdminJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddAdminMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddAdminAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddAdminDateNaissance)
                    .addComponent(jLabelAddAdminMail)
                    .addComponent(jTextFieldAddAdminMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddAdminPassword)
                    .addComponent(jPasswordFieldAddAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldAddAdminPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddAdminPasswordConfirm))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAddAdminAdresse)
                    .addComponent(jTextFieldAddAdminAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddVilleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAddVilleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonAddAdmin)
                .addGap(118, 118, 118))
        );

        jTabbedPanelCours.addTab("Créer un administrateur", jPanel5);

        jButton3.setText("jButton3");

        jButtonSearchUsers.setText("rechercher");
        jButtonSearchUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUsersActionPerformed(evt);
            }
        });

        jCheckBoxAdmin.setText("administrateurs");

        jCheckBoxCuisinier.setText("cuisiniers");

        jCheckBoxClient.setText("clients");

        jCheckBoxAll.setText("tout cocher");
        jCheckBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAllActionPerformed(evt);
            }
        });

        jCheckBoxNoOne.setText("tout décocher");
        jCheckBoxNoOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNoOneActionPerformed(evt);
            }
        });

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableUsers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSearchUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAdmin)
                            .addComponent(jButtonSearchUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(jCheckBoxCuisinier)
                            .addComponent(jCheckBoxClient)
                            .addComponent(jCheckBoxAll)
                            .addComponent(jCheckBoxNoOne))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextFieldSearchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonSearchUsers)
                .addGap(22, 22, 22)
                .addComponent(jCheckBoxAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCuisinier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxNoOne)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        jTabbedPanelCours.addTab("Les utilisateurs", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelCours))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelCours)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIngredientActionPerformed
        // TODO add your handling code here:
        String categorie = (String)jComboBoxChooseCategorieIngredient.getSelectedItem();
        String nom = jTextFieldAddIngrédient.getText();
        model.ModelIngredient.addIngredient(nom, categorie);
        
    }//GEN-LAST:event_jButtonAddIngredientActionPerformed

    private void jTextFieldAddAdminJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddAdminJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddAdminJourActionPerformed

    private void jButtonAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAdminActionPerformed
        String nom = jTextFieldAddAdminNom.getText();
        String prenom = jTextFieldAddAdminPrenom.getText();
        String password = new String(jPasswordFieldAddAdminPassword.getPassword());
        String passwordConfirm = new String(jPasswordFieldAddAdminPasswordConfirm.getPassword());
        String annee = jTextFieldAddAdminAnnee.getText();
        String mois = jTextFieldAddAdminMois.getText();
        String jour = jTextFieldAddAdminJour.getText();
        //String ville = (String)jComboBoxAddVilleUser.getSelectedItem();
        //String dateNaissance = jTextFieldAddAdminAnnee.getText() + "-" + jTextFieldAddAdminMois.getText()+ "-" + jTextFieldAddAdminJour.getText();

        System.out.println(password);

        Boolean userInBase = model.ModelUtilisateurs.verifyUser(nom, prenom);

        if (!nom.isEmpty() && !prenom.isEmpty()) {
            if (userInBase == false) {

                if (!annee.isEmpty() && !mois.isEmpty() && !jour.isEmpty()) {
                    if (password.equals(passwordConfirm)) {
                        int nbAnnee = Integer.parseInt(jTextFieldAddAdminAnnee.getText());
                        int nbMois = Integer.parseInt(jTextFieldAddAdminMois.getText());
                        int nbJour = Integer.parseInt(jTextFieldAddAdminJour.getText());

                        if (nbAnnee > 1900 && nbAnnee < 2020) {
                            if (nbMois > 0 && nbMois < 13) {
                                if (nbJour > 0 && nbJour < 32) {

                                    if (nbJour > 28 && nbMois == 2
                                        && ((nbAnnee % 4 != 0 || nbAnnee % 100 == 0))
                                        && nbAnnee % 400 != 0) {

                                        JOptionPane.showMessageDialog(this, "L'année sélectionnée n'est pas bisextile");

                                    } else {

                                        //Récupération des autres valeurs
                                        String ville = (String) jComboBoxAddVilleUser.getSelectedItem();
                                        String adresse = jTextFieldAddAdminAdresse.getText();
                                        String mail = jTextFieldAddAdminMail.getText();

                                        //Concaténation de la date
                                        String dateNaissance = annee + "-" + mois + "-" + jour;
                                        //Insertion
                                        model.ModelUtilisateurs.addUserAdmin(nom, prenom, dateNaissance, adresse, ville, password, mail);
                                    }

                                } else {
                                    JOptionPane.showMessageDialog(this, "Mauvais jour");
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Mauvais mois");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Mauvaise année");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Les deux mots de passes ne correspondent pas !");
                    }
                } else {
                    model.ModelUtilisateurs.updateUserToAdmin(nom, prenom);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Le prénom et / ou le nom n'est pas renseigné");
            }
        }
    }//GEN-LAST:event_jButtonAddAdminActionPerformed

    private void jTextFieldAddVilleUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddVilleUserKeyPressed
        jComboBoxAddVilleUser.removeAllItems();
        int longueurChaine = jTextFieldAddVilleUser.getText().length();
        if (longueurChaine >= 3) {
            ArrayList result = model.ModelVille.selectVille(jTextFieldAddVilleUser.getText());

            for (int i = 0; i < result.size(); i++) {
                jComboBoxAddVilleUser.addItem((String) result.get(i));
            }
        }
    }//GEN-LAST:event_jTextFieldAddVilleUserKeyPressed

    private void jTextFieldAddVilleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddVilleUserActionPerformed

    }//GEN-LAST:event_jTextFieldAddVilleUserActionPerformed

    private void jCheckBoxNoOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNoOneActionPerformed
        jCheckBoxAdmin.setSelected(false);
        jCheckBoxClient.setSelected(false);
        jCheckBoxCuisinier.setSelected(false);
        jCheckBoxAll.setSelected(false);
    }//GEN-LAST:event_jCheckBoxNoOneActionPerformed

    private void jCheckBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAllActionPerformed
        jCheckBoxAdmin.setSelected(true);
        jCheckBoxClient.setSelected(true);
        jCheckBoxCuisinier.setSelected(true);
        jCheckBoxNoOne.setSelected(false);
    }//GEN-LAST:event_jCheckBoxAllActionPerformed

    private void jButtonSearchUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUsersActionPerformed
        String nom = jTextFieldSearchUsers.getText();
        String prenom = jTextField1.getText();

        ResultSet resultAllUsers = model.ModelUtilisateurs.selectParticularUsersWithConditions(nom, prenom, jCheckBoxClient.isSelected(), jCheckBoxCuisinier.isSelected(), jCheckBoxAdmin.isSelected());
        jTableUsers.setModel(DbUtils.resultSetToTableModel(resultAllUsers));
    }//GEN-LAST:event_jButtonSearchUsersActionPerformed

    private void jButtonSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCategoryActionPerformed
        String searchCategory = jTextFieldSearchCategory.getText();

        ResultSet resultOneCategory = model.ModelCategorie.selectOneCategory(searchCategory);
        jTableCategory.setModel(DbUtils.resultSetToTableModel(resultOneCategory));
    }//GEN-LAST:event_jButtonSearchCategoryActionPerformed

    private void jButtonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCategoryActionPerformed
        String nomCategory = jTextFieldAddCategory.getText();
        String descriptionCategory = jTextAreaAddCategory.getText();

        model.ModelCategorie.createCategory(nomCategory, descriptionCategory);

        fillJTableCategory();

        jTextAreaAddCategory.setText("");
        jTextFieldAddCategory.setText("");
    }//GEN-LAST:event_jButtonAddCategoryActionPerformed

    private void jTextFieldChooseCategorieIngredientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldChooseCategorieIngredientKeyPressed
        // TODO add your handling code here:
        jComboBoxChooseCategorieIngredient.removeAllItems();
        int longueurChaine = jTextFieldChooseCategorieIngredient.getText().length();
        if (longueurChaine >= 3) {
            ArrayList result = model.ModelCategorie.selectCategorie(jTextFieldChooseCategorieIngredient.getText());

            for (int i = 0; i < result.size(); i++) {
                jComboBoxChooseCategorieIngredient.addItem((String) result.get(i));
            }
        }
    }//GEN-LAST:event_jTextFieldChooseCategorieIngredientKeyPressed

    private void jButtonAddRecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRecetteActionPerformed
        // TODO add your handling code here:
        String nom = jTextFieldAddRecette.getText();
        String description = jTextAreaAddRecette.getText();
        
        System.err.println(arrayListIngredients);
        
        model.ModelRecette.addRecette(nom, description);
        
        model.ModelRecette.addRecetteIngredients(nom, arrayListIngredients);
    }//GEN-LAST:event_jButtonAddRecetteActionPerformed

    private void jTextFieldListIngredientsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldListIngredientsKeyPressed
        // TODO add your handling code here:
        jComboBoxListIngredients.removeAllItems();
            ArrayList result = model.ModelIngredient.selectParticularIngredients(jTextFieldListIngredients.getText());

            for (int i = 0; i < result.size(); i++) {
                jComboBoxListIngredients.addItem((String) result.get(i));
            }
    }//GEN-LAST:event_jTextFieldListIngredientsKeyPressed

    private void jButtonAddIngredientToRecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIngredientToRecetteActionPerformed
        // TODO add your handling code here:
        String ingredientsInRecette = "";
        
        jLabelListIngredients.setText("");
        if(!arrayListIngredients.contains((String)jComboBoxListIngredients.getSelectedItem())){
            arrayListIngredients.add((String)jComboBoxListIngredients.getSelectedItem());
        }
        System.out.println(arrayListIngredients.size());
        
        for(int i = 0; i < arrayListIngredients.size(); i++){
            
            ingredientsInRecette += arrayListIngredients.get(i)+" , ";
            }
        
        jLabelListIngredients.setText(ingredientsInRecette);
        
    }//GEN-LAST:event_jButtonAddIngredientToRecetteActionPerformed

    /**jComboBoxChooseIngredientItemStateChanged
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddAdmin;
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonAddIngredient;
    private javax.swing.JButton jButtonAddIngredientToRecette;
    private javax.swing.JButton jButtonAddRecette;
    private javax.swing.JButton jButtonSearchCategory;
    private javax.swing.JButton jButtonSearchUsers;
    private javax.swing.JCheckBox jCheckBoxAdmin;
    private javax.swing.JCheckBox jCheckBoxAll;
    private javax.swing.JCheckBox jCheckBoxClient;
    private javax.swing.JCheckBox jCheckBoxCuisinier;
    private javax.swing.JCheckBox jCheckBoxNoOne;
    private javax.swing.JComboBox<String> jComboBoxAddVilleUser;
    private javax.swing.JComboBox<String> jComboBoxChooseCategorieIngredient;
    private javax.swing.JComboBox<String> jComboBoxListIngredients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddAdminAdresse;
    private javax.swing.JLabel jLabelAddAdminDateNaissance;
    private javax.swing.JLabel jLabelAddAdminMail;
    private javax.swing.JLabel jLabelAddAdminNom;
    private javax.swing.JLabel jLabelAddAdminPassword;
    private javax.swing.JLabel jLabelAddAdminPasswordConfirm;
    private javax.swing.JLabel jLabelAddAdminPrenom;
    private javax.swing.JLabel jLabelChooseCategorieIngredient;
    private javax.swing.JLabel jLabelListIngredients;
    private javax.swing.JLabel jLabelNomIngrédient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldAddAdminPassword;
    private javax.swing.JPasswordField jPasswordFieldAddAdminPasswordConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPanelCours;
    private javax.swing.JTable jTableCategory;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextArea jTextAreaAddCategory;
    private javax.swing.JTextArea jTextAreaAddRecette;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAddAdminAdresse;
    private javax.swing.JTextField jTextFieldAddAdminAnnee;
    private javax.swing.JTextField jTextFieldAddAdminJour;
    private javax.swing.JTextField jTextFieldAddAdminMail;
    private javax.swing.JTextField jTextFieldAddAdminMois;
    private javax.swing.JTextField jTextFieldAddAdminNom;
    private javax.swing.JTextField jTextFieldAddAdminPrenom;
    private javax.swing.JTextField jTextFieldAddCategory;
    private javax.swing.JTextField jTextFieldAddIngrédient;
    private javax.swing.JTextField jTextFieldAddRecette;
    private javax.swing.JTextField jTextFieldAddVilleUser;
    private javax.swing.JTextField jTextFieldChooseCategorieIngredient;
    private javax.swing.JTextField jTextFieldListIngredients;
    private javax.swing.JTextField jTextFieldSearchCategory;
    private javax.swing.JTextField jTextFieldSearchUsers;
    // End of variables declaration//GEN-END:variables
}
